services:

  app:
    build:
      context: ./app
      args:
        - DATABASE_URL=postgresql://patient-db:patient-db-password@host.docker.internal:5432/patient-db?schema=public
        - MODEL_API_URL=http://host.docker.internal:8080
    container_name: app
    environment:
      - DATABASE_URL=postgresql://patient-db:patient-db-password@db:5432/patient-db?schema=public
      - MODEL_API_URL=http://api:8080
    ports:
      - 3000:3000

  api:
    build: ./api
    container_name: api
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  db:
    image: postgres:16.2
    container_name: db
    environment:
      - POSTGRES_PASSWORD=patient-db-password
      - POSTGRES_USER=patient-db
      - POSTGRES_DB=patient-db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  db-data:
