services:
  db:
    image: postgres:16.2
    container_name: hmi-db
    environment:
      - POSTGRES_PASSWORD=patient-db-password
      - POSTGRES_USER=patient-db
      - POSTGRES_DB=patient-db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  db-data:
