FROM node:20 AS base
ARG DATABASE_URL
ARG MODEL_API_URL
ENV NEXT_TELEMETRY_DISABLED 1
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app
RUN pnpm install --frozen-lockfile
RUN chmod +x ./build_run.sh
CMD ./build_run.sh